# Generated by Django 4.0.4 on 2022-09-08 12:26

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=1001)),
                ('file', models.FileField(upload_to='foto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Pending', 'Pending'), ('Read', 'Read')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioPerzonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('userDocumento', models.CharField(choices=[('Cedula de ciudadania', 'Cedula de ciudadania'), ('Tarjeta de identidad', 'Tarjeta de identidad'), ('Cédula de extranjería', 'Cédula de extranjería')], max_length=200)),
                ('userNombreCompleto', models.CharField(max_length=20)),
                ('userApellidos', models.CharField(max_length=30)),
                ('userSexo', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Intersexual', 'Intersexual'), ('Indefinido', 'Indefinido'), ('Prefieren no decir', 'Prefieren no decir')], max_length=20)),
                ('userTelefono', models.CharField(max_length=11)),
                ('userTelefonoFijo', models.CharField(max_length=11)),
                ('userCorreo', models.EmailField(max_length=20)),
                ('userMunicipio', models.CharField(max_length=10)),
                ('userDireccion', models.CharField(blank=True, max_length=30, null=True)),
                ('userBarrio', models.CharField(max_length=100)),
                ('userFechaNacimiento', models.DateField(blank=True, null=True)),
                ('userEtnia', models.CharField(max_length=30)),
                ('userCondicionDiscapacidad', models.CharField(max_length=60)),
                ('userEstrato', models.CharField(max_length=3)),
                ('userUltimoNivelEducativo', models.CharField(max_length=25)),
                ('userDispositivo', models.BooleanField(default=False, max_length=100)),
                ('userTipoDispositivo', models.CharField(choices=[('T. Móvil', 'T. Móvil'), ('Computador', 'Computador'), ('Tablet', 'Tablet'), ('Otro', 'Otro')], max_length=100)),
                ('userConectividad', models.BooleanField(default=False, max_length=100)),
                ('userTipoAfiliacion', models.CharField(choices=[('Subsidiado', 'Subsidiado'), ('contributivo', 'contributivo')], max_length=100)),
                ('userProfile', models.ImageField(blank=True, upload_to='profile_pics')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Sondeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sonTipo', models.CharField(choices=[('Pregunta', 'Pregunta'), ('Fecha', 'Fecha'), ('Opciones de respuesta', 'Opciones de respuesta')], max_length=100)),
                ('sonTitulo', models.CharField(max_length=100)),
                ('sonFechaApertura', models.DateField()),
                ('sonHoraApertura', models.TimeField()),
                ('sonFechaCierre', models.DateField()),
                ('sonHoraCierre', models.TimeField()),
                ('sonRespuesta', models.CharField(max_length=100)),
                ('sonObservaciones', models.CharField(max_length=100)),
                ('encuesta', models.ManyToManyField(to='App.encuesta')),
            ],
            options={
                'db_table': 'sondeo',
            },
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100)),
                ('resultado', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='App.encuesta')),
            ],
        ),
    ]
